# Generated by Django 4.2.6 on 2023-10-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('type', models.CharField(choices=[('hit', 'Хит'), ('all', 'общие'), ('sponsor', 'реклама')], default='all', max_length=50, verbose_name='Тип')),
                ('price', models.IntegerField(max_length=50, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'список товаров',
            },
        ),
    ]
